BINDING_HEADER_R2D2 = "thpack.r2d2"
BINDING_NAME_TOGGLE_MACRO_FRAME = "Toggle Macro Frame"
BINDING_NAME_TOGGLE_WORLD_MAP_FRAME = "Toggle World Map Frame"
BINDING_NAME_TOGGLE_BATTLEGROUND_SCOREBOARD = "Toggle Battleground Scoreboard"
